RecipeBook/RecipeBook/urls.py
from django.conf.urls.defaults import *
from django.views.generic import DetailView, ListView
from RecipeBook.models import Source,Recipe,Ingredient

from django.views.generic.simple import direct_to_template
from RecipeBook.views import index_page

urlpatterns = patterns('',
	('^index/$', direct_to_template, {'template': 'index.html'}),

	url(r'^listing$',   ### need index page ---> {Source/Recipe listings}
    	ListView.as_view(
        	queryset=Recipe.objects.order_by('name'),
        	context_object_name='recipe_list',
        	template_name='RecipeBook/recipeList.html')),

	url(r'^sources$',
    	ListView.as_view(
        	queryset=Source.objects.order_by('name'),
        	context_object_name='source_list',
        	template_name='RecipeBook/sourceList.html')),

	url(r'^Recipes$',
    	ListView.as_view(
        	queryset=Recipe.objects.order_by('name'),
        	context_object_name='recipe_list',
        	template_name='RecipeBook/recipeList.html')),
	url(r'^(?P<pk>\d+)/$',
    	DetailView.as_view(
        	model=Recipe,
        	template_name='RecipeBook/detail.html')),
)

RecipeBook/config/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'RecipeBook.views.home', name='home'),
    url(r'^RecipeBook/', include('RecipeBook.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

RecipeBook/RecipeBook/models.py
from django.db import models

# Create your models here.

class Source(models.Model):
    name = models.CharField(max_length=100)
    url = models.CharField(max_length=100, blank=True)
    # type = {book, magazine, url, image}  ### <--- add this !
    def __unicode__(self):
   	 return self.name

class Recipe(models.Model):
    name = models.CharField(max_length=100)
    notes = models.TextField(max_length=200, blank=True)
    #
    source = models.ForeignKey(Source)
    srcPage = models.CharField(max_length=20, blank=True)
    srcURL = models.CharField(max_length=200, blank=True)
    #
    #ingredients = models.ManyToManyField(Ingredient, through = 'IngredientList')  # <-- need to try this
    #
    def __unicode__(self):
   	 return self.name

class Ingredient(models.Model):
    name = models.CharField(max_length=200)
    def __unicode__(self):
   	 return self.name

class IngredientList(models.Model):
    recipe = models.ForeignKey(Recipe)
    ingredient = models.ForeignKey(Ingredient)
    quantity = models.CharField(max_length=50)
    units = models.CharField(max_length=50, blank=True)	

RecipeBook/RecipeBook/views.py
# Create your views here.
from django.http import Http404
from django.template import TemplateDoesNotExist
from django.views.generic.simple import direct_to_template

def index_page(request, page):
    try:
        return direct_to_template(request, template="index.html")
    except:
        raise Http404()

RecipeBook/RecipeBook/templates/RecipeBook/detail.html
<html>

<script src="{{ STATIC_URL }}/ratio/lib/Ratio.js"></script>
<script src="{{ STATIC_URL }}recipeSupport.js"></script>
<script>

function compute(){
    var myTable=document.getElementById('ingredients').rows;
    var source;
    var newNum;
    var scale=document.getElementById('scale').options;
    var factorIndex=document.getElementById('scale').selectedIndex;
    var factor = scale[factorIndex].text;
    for (var row=1; row < myTable.length; row++) {
        source=myTable[row].cells[1].innerHTML;
        newNum=convert(source,factor);
        myTable[row].cells[3].innerHTML=formatOutput(newNum,"");
    }
}

</script>


<link rel="stylesheet" href="{{ STATIC_URL }}rbook.css" type="text/css">

<!--  not sure how to reference image from within *.css file --!>
<style>
  body { background-image: url({{ STATIC_URL }}FeatherTexture.bmp) }
</style>

<body>
<h1>{{ recipe.name }}</h1>

<p class="source"> {{ recipe.source.name }}
{% if recipe.srcPage != "" %} - page {{ recipe.srcPage }} {% endif %}
{% if recipe.srcURL != "" %} (<a href="{{recipe.srcURL}}">source</a>) {% endif %}
</p>

<p class="notes"> {{ recipe.notes }} </p>

<h3>Ingredient list</h3>

<form method="post" name="conversionTable">

<ul>
{% for ingredientListItem in recipe.ingredientlist_set.all %}  {# table_set forced to lower case? #}
    <li> {{ ingredientListItem.ingredient.name }}: {{ ingredientListItem.quantity }} {{ ingredientListItem.units }} </li>
{% endfor %}
</ul>

<table id="ingredients" border=1>
 <tr> <th> Ingredient </th><th colspan=2> Quantity </th> <th colspan=2> Rescaled</th> </tr>
{% for ingredientListItem in recipe.ingredientlist_set.all %}
 <tr> <td> {{ ingredientListItem.ingredient.name }} </td>
      <td> {{ ingredientListItem.quantity }} </td>
      <td> {{ ingredientListItem.units }} </td>
      <td> {{ ingredientListItem.quantity }} </td>
      <td> {{ ingredientListItem.units }} </td>
 </tr>
{% endfor %}
</table>

Scale:
<select id="scale" onchange="compute()">
<option value="3">3</option>
<option value="2">2</option>
<option value="1" selected="selected">1</option>
<option value="1/2">1/2</option>
<option value="1/3">1/3</option>
</select>


</form>

</body>
</html>

RecipeBook/RecipeBook/templates/RecipeBook/recipeList.html
<href>
<link rel="stylesheet" href="{{ STATIC_URL }}rBook.css" type="text/css">

<!--  not sure how to reference image from within *.css file --!>
<style>
  body { background-image: url({{ STATIC_URL }}FeatherTexture.bmp) }
</style>

<body>
{% if recipe_list %}
  <h1> List of my recipes</h1>
	<ul>
	{% for recipe in recipe_list %}
    	<li><a href="/RecipeBook/{{ recipe.id }}/">{{ recipe.name }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No recipes are available.</p>
{% endif %}
<a href="/RecipeBook/sources">source listing</a>

</body>
</html>

RecipeBook/RecipeBook/templates/RecipeBook/search.html
<html>
<link rel="stylesheet" href="{{ STATIC_URL }}rbook.css" type="text/css">

<!--  not sure how to reference image from within *.css file --!>
<style>
  body { background-image: url({{ STATIC_URL }}woodSurface.JPG) }
</style>

<body>
{% if source_list %}
  <h1> List of my sources </h1>
	<ul>
	{% for source in source_list %}
  	{% if source.url != "n/a" %} <li><a href="{{ source.url }}">{{ source.name }}</a></li>
  	{% else %} <li>{{ source.name }}</li>
  	{% endif %}
	{% endfor %}
	</ul>
{% else %}
	<p>No sources are available.</p>
{% endif %}
</body>
</html>

RecipeBook/RecipeBook/templates/RecipeBook/sourceList.html
<html>
<link rel="stylesheet" href="{{ STATIC_URL }}rbook.css" type="text/css">

<!--  not sure how to reference image from within *.css file --!>
<style>
  body { background-image: url({{ STATIC_URL }}SantaFeStucco.bmp) }
</style>

<body>
{% if source_list %}
  <h1> List of my sources </h1>
	<ul>
	{% for source in source_list %}
  	{% if source.url != "n/a" %} <li><a href="{{ source.url }}">{{ source.name }}</a></li>
  	{% else %} <li>{{ source.name }}</li>
  	{% endif %}
	{% endfor %}
	</ul>
{% else %}
	<p>No sources are available.</p>
{% endif %}
</body>
</html>

RecipeBook/RecipeBook/templates/index.html
<html>
<link rel="stylesheet" href="{{ STATIC_URL }}rbook.css" type="text/css">

<!--  not sure how to reference image from within *.css file --!>
<style>
  body { background-image: url({{ STATIC_URL }}IMG_2672.jpg); background-size=100% }
</style>

<body>
<h1> My Recipe book </h1>
<nav><ul>
  <li><a href="/RecipeBook/listing">Recipe List</a> </li>
  <li><a href="/RecipeBook/sources">Source List</a> </li>
  <li><a href="/RecipeBook/search">Search for Recipe</a> </li>
</ul></nav>

</body>
</html>